### ISSUE TITLE
Checkboxlist instead of typeahead combo box

### ISSUE THREAD

**Issue by OndrejValenta** [vert-x3/vertx-starter#111] opened 2019-06-19 22:19 UTC
### Context

Could we change the typeahead combobox with possible dependencies to standard checkbox list because this way user can see all the options and does not have to type a, b, c, d, e and so on to get all possible modules. 

We could even go as far as to group those modules into groups like monitoring, web related, api related and so on..

![image](https://user-images.githubusercontent.com/6738956/59805150-bfd93400-92f0-11e9-80b1-bcfc4a4af279.png)

### Steps to reproduce

1. Open https://start.vertx.io/

**Comment by tsegismont** [comment] 2019-06-20 08:51
Related to the same problem, we have #97 (and a POC in #101 ).

AFAIC, I would prefer a panel because a long combo box is not fun to scroll and does not allow to add some extra info about the module.

**Comment by OndrejValenta** [comment] 2019-06-22 19:00
![image](https://user-images.githubusercontent.com/6738956/59967850-9d355e00-9530-11e9-9897-63fafdc302c5.png)

I've got a first version almost working but for some reason nav-tabs do not work. Perhaps bootstrap javascript files are not loaded or something

**Comment by OndrejValenta** [comment] 2019-06-22 23:23
![2019-06-23_01-12-41](https://user-images.githubusercontent.com/6738956/59969718-e4cde100-9554-11e9-9be0-5a2c9e8434ee.gif)

New version commited here.. I will clean it up a little bit and it's ready to be tested properly.

Commit: https://github.com/KeenMate/vertx-starter/commit/fcf50eda0df56811be10c1ccb05a71ac8a6a8613

**Comment by tsegismont** [comment] 2019-06-23 11:19
@OndrejValenta very cool! I'll give it a try asap.

**Comment by danielpetisme** [comment] 2019-06-23 11:25
Great! I :+1: Thomas panel idea.
IMHO, the panel with all options groupped by category provides a better UX (keeping the main page very lean).

**Comment by OndrejValenta** [comment] 2019-06-23 11:29
I'm glad you like it.

**Comment by OndrejValenta** [comment] 2019-06-29 16:25
So should I make a pull request? :-)

**Comment by tsegismont** [comment] 2019-06-30 14:20
Hi Ondrej, I was out of office for a conference this week. I will give a
try to your changes tomorrow.

**Comment by OndrejValenta** [comment] 2019-07-01 03:47
Of course, of course, I just didn't want this to die. :-) Take your time.

**Comment by tsegismont** [comment] 2019-07-01 15:24
@OndrejValenta good job! I haven't looked at the code thoroughly, but the behavior is exactly what we want. On the presentation side, it would be better to have the panel as a popup or collapsible though. Otherwise you have to scroll down to the generate button even when you know what you want.

**Comment by OndrejValenta** [comment] 2019-07-01 21:49
I'm personally not a big fan of popups an dialogs, for me they break up the UI flow, so I was more thinking about keeping the typeahead combo and next to it would be a button displaying "Detailed options" and that would open the tabbed preview of all modules.

**Comment by tsegismont** [comment] 2019-07-02 07:20
Detailed option button with collapsible panel would do great! Looking forward to the PR :wink: 

By the way, I noticed you were not very fond of Angular on the Gitter channel. Which technology do you think would fit best for this site? If you can propose a refactoring with a SPA toolchain, we can discuss that.

Anyway, thanks again for the prototype.

**Comment by OndrejValenta** [comment] 2019-07-02 11:35
Ok, so this question is a little bit more complex. Generally speaking whatever javascript library you learn will work for you to some extent. Look at me, I've never used Angular and still was able to make changes in your code and was fine with it. I'm beyond hunting down the latest technologies just because they are in a spotlight. I was like that for several years and it leads to sadness and frustration. I know that people in DHL and CGI still use jQuery and they are happy about it. It's simple enough for them to use and they plan their UI according to jQuery capabilities. 

Now, to more real stuff. Most of the people would probably suggest React because it is sooo popular these days, like 70%. Our (me and my boys) shared experience is that although React will change you forever with its principles of pure components, as well as a mind is changed when it first touches pure functions in functional languages, the real work with it is painful. You have to boost it with some kind of "state management" tool like MobX otherwise your hair will grey of constant calling setState() method.
Boosting it with MobX would actually make React more like VueJS and at that point you can just switch to VueJS that is more friendly to use.

VueJS is our primary framework, it suitable for small projects like this form to whole SPA, although when it gets bigger it's getting harder to keep code cleanness and structure (perhaps, this applies to all of them). VueJS is like Kotlin, you can be functional but you are mainly OOP, so you have both worlds. You can be also more creative with your code and it lets you do some funky stuff. :-) 

And lastly, from my side, there is https://svelte.dev/ that is a framework of next generation. All of the previous frameworks, angular, jquery, react, vuejs and many others live within constraints of Javascript language so it's you programmer, that has to deal with a lot of unnecessary code like e.g. calling setState() method. Svelte moved a lot of boilerplating into their compiler and the code you have to write is truly minimal and it's even faster to run. I was actually thinking of rewriting it all to svelte just to see how small the form code would be.

**Comment by tsegismont** [comment] 2019-07-02 12:14
Ok, can you capture the options in a separate issue? I have my preference but I'd prefer we discuss it there. Thanks for sharing your thoughts.

**Comment by OndrejValenta** [comment] 2019-07-05 00:30
@tsegismont  I think we have reached the end of this journey. :-) I've added back the typeahead combo, fixed some issues with missing .row classes, removed uib-collapse that were sluggish and replaced them with simple ng-hide/show and added automatic scrolling, added a global arrow that takes to to generate button, changed the filtering so you cannot add the same dependency twice and few more changes.. Added also main.css, btw.

![2019-07-05_02-16-22](https://user-images.githubusercontent.com/6738956/60691033-c066f280-9ecc-11e9-9ddf-fba7c0a3eb92.gif)


Commit: https://github.com/KeenMate/vertx-starter/commit/36381f83a32137483d2eecc1b3c5a0b57137abfc

**Comment by tsegismont** [comment] 2019-07-05 06:11
Can you open a PR then?

Le ven. 5 juil. 2019 à 02:30, Ondrej Valenta <notifications@github.com> a
écrit :

**Comment by OndrejValenta** [comment] 2019-07-06 16:33
Done. :-)

**Comment by tsegismont** [comment] 2019-08-26 12:50
Closed as duplicate of #97

**Closed by tsegismont** 2019-08-26 12:50 UTC
Labels: duplicate

**Comment by OndrejValenta** [comment] 2019-09-20 23:34
Sorry, I've been busy lately but I'm glad it's already running. I hope users noticed and feel like this is a better user experience. :-)

**Comment by tsegismont** [comment] 2019-09-21 10:45
They certainly do. I do 😉

Le sam. 21 sept. 2019 à 01:34, Ondrej Valenta <notifications@github.com> a
écrit :
